// This file is automatically generated. Do not edit it directly unless you know what you're doing.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';

// Preferred env names used by Vite + this project
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
// Prefer the anon/public key name, but fall back to older "publishable" name
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY ?? import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
  const missing: string[] = [];
  if (!SUPABASE_URL) missing.push('VITE_SUPABASE_URL');
  if (!SUPABASE_ANON_KEY) missing.push('VITE_SUPABASE_ANON_KEY (or VITE_SUPABASE_PUBLISHABLE_KEY)');
  // eslint-disable-next-line no-console
  console.error('[supabase] Missing env vars:', missing.join(', '));
  throw new Error(`[supabase] Missing required environment variables: ${missing.join(', ')}. See README for setup instructions.`);
}

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    storage: brokeredPreviewStorage(),
    persistSession: true,
    autoRefreshToken: true,
  },
});
